name: morphotrack
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=2.10.0
  - netcdf4=1.5.7
  - scipy=1.7.3
  - setuptools=58.0.4
  - xarray=2022.6.0
  - pip=22.2.2
  - python=3.8.10
  - pip:
    - jupyterlab==3.2.1
    - napari==0.4.15
    - networkx==2.6.3
    - nibabel==3.2.1
    - pandas==1.3.4
    - pydeform==0.5.1
    - ray==1.7.1
    - scikit-image==0.19.3
    - scikit-learn==1.0
    - seaborn==0.11.2
    - statsmodels==0.13.0
    - tifffile==2021.10.12
    - tqdm==4.62.3
    - umap-learn==0.5.3
    - vispy==0.9.6
    - protobuf==3.20
    - alphashape==1.3.1
    - simpleitk==2.1.1
